### ISSUE TITLE
Filter_ID:  "file will not be a valid QuakeML file"

### ISSUE THREAD

**Issue by fordgeoscience** [crotwell/pickax#6]
Ashley's Error:  After completing some picks this morning, I noticed these comments in the log. The message seems to be inferring that the picks I made while using one of the filters will 'not be a valid QuakeML file'. 

_"UserWarning: 'bandpass 1 10' is not a valid QuakeML URI. It will be in the final file but note that the file will not be a valid QuakeML file."_

Phillip's Response:  The issue is that I put in the filter_id in the QuakeML Arrival object as just whatever the name of the filter is. However, QuakeML has a rather strict opinion of the structure of an "id"...I should make a legit filter_id eventually, but just ignore until then."

**Comment by crotwell** [comment]
fixed in https://github.com/crotwell/pickax/commit/251f4d6665d6703ad25d261c5b615a60dcef72d1
